modLoader="javafml"
loaderVersion="[43,)"

license="GNU GPLv3"

[[mods]]
modId="complexity"
version="${file.jarVersion}"
displayName="Complexity"
authors="lummwastaken"
description='''Minecraft gameplay overhaul for increased immersion and depth'''

[[dependencies.complexity]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.complexity]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
